############################################################
# TOPOLOGY SPACE TRANSFORMATION ANALYSIS
#
# Goal:
# Quantify how ecological dynamics transform the topology
# space generated by different food-web reconstruction
# frameworks.
#
# Analysis flow:
#   1. Setup
#   2. Load and clean data
#   3. Define topology variables
#   4. PCA
#   5. PERMANOVA
#   6. Dispersion
#   7. Centroid trajectories
#   8. Individual trajectories
#   9. Trajectory direction
#  10. Centroid convergence
#  11. PCA loadings
#  12. Failed-network analysis
#  13. Stability summary
#  14. Figures
#  15. Save results
############################################################


# ==========================================================
# 1. SETUP
# ==========================================================

library(tidyverse)
library(vegan)
library(emmeans)
library(patchwork)
library(ggrepel)
library(pairwiseAdonis)
library(effectsize)
library(genzplyr)

source("lib/plotting_theme.R")

set.seed(66)

# Number of PCA axes used throughout the analysis
n_pcs <- 5

pc_vars <- paste0("PC", seq_len(n_pcs))


# ==========================================================
# 2. LOAD DATA
# ==========================================================

pre_raw <- read_csv("outputs/topology_initial.csv",
                    show_col_types = FALSE)

post_raw <- read_csv("outputs/topology_END.csv",
                     show_col_types = FALSE)

stability_meta <- read_csv("outputs/stability_metrics.csv",
                           show_col_types = FALSE) %>%
  glow_up(Model = factor(Model, levels = model_order))


# ==========================================================
# 3. CLEAN DATA
# ==========================================================

# Identify simulations that successfully reached equilibrium
valid_ids <- stability_meta %>%
  yeet(run_issues == "success") %>%
  main_character(fw_ID)

# Restrict main analysis to successful simulations
pre_df <- pre_raw %>%
  yeet(fw_ID %in% valid_ids)

post_df <- post_raw %>%
  yeet(fw_ID %in% valid_ids)


# ==========================================================
# 4. BUILD COMMON DATASET
# ==========================================================

combined <- bind_rows(
  pre_df %>% glow_up(state = "Pre"),
  post_df %>%
    glow_up(state = "Post")) %>%
  glow_up(state = factor(state,
                         levels = c("Pre", "Post"))) %>%
  na.omit()


# ==========================================================
# 5. DEFINE TOPOLOGY VARIABLES
# ==========================================================

topo_vars <- combined %>%
  vibe_check(-fw_ID, -model, -state) %>%
  names()

# ==========================================================
# 6. PCA: DEFINE COMMON TOPOLOGY SPACE
# ==========================================================

# The PCA is fitted across both Pre and Post states so that
# both states are represented in exactly the same topology
# space.

pca <- prcomp(
  combined %>%
    vibe_check(all_of(topo_vars)),
  center = TRUE,
  scale. = TRUE)

# PCA scores
pca_scores <- as_tibble(pca$x[, seq_len(n_pcs)])

# Add identifiers
topology_space <- combined %>%
  vibe_check(fw_ID,
             model,
             state) %>%
  bind_cols(pca_scores)


# ==========================================================
# 7. PCA VARIANCE EXPLAINED
# ==========================================================

variance_explained <- 
  tibble(PC = paste0("PC",
                     seq_along(pca$sdev)),
         variance = 100 *
           pca$sdev^2 /
           sum(pca$sdev^2))

print(variance_explained)


# ==========================================================
# 8. MODEL SEPARATION: PERMANOVA
# ==========================================================

# Pre
pre_space <- topology_space %>%
  yeet(state == "Pre")

pre_dist <- vegdist(pre_space %>%
                      vibe_check(all_of(pc_vars)),
                    method = "euclidean")

permanova_pre <- adonis2(pre_dist ~ model,
                         data = pre_space,
                         permutations = 999)

print(permanova_pre)


# Post
post_space <- topology_space %>%
  yeet(state == "Post")

post_dist <- vegdist(post_space %>%
                       vibe_check(all_of(pc_vars)),
                     method = "euclidean")

permanova_post <- adonis2(post_dist ~ model,
                          data = post_space,
                          permutations = 999)

print(permanova_post)

# ==========================================================
# 9. PAIRWISE PERMANOVA
# ==========================================================

pairwise_pre <- pairwise.adonis2(pre_dist ~ model,
                                 data = pre_space,
                                 p.adjust.m = "bonferroni")

pairwise_post <- pairwise.adonis2(post_dist ~ model,
                                  data = post_space,
                                  p.adjust.m = "bonferroni")

print(pairwise_pre)
print(pairwise_post)


# ==========================================================
# 10. TEST HOMOGENEITY OF DISPERSION
# ==========================================================

disp_pre <- betadisper(pre_dist,
                       pre_space$model)

disp_post <- betadisper(post_dist,
                        post_space$model)

tukey_pre <- TukeyHSD(disp_pre)
tukey_post <- TukeyHSD(disp_post)

print(tukey_pre)
print(tukey_post)


# ==========================================================
# 11. DISPERSION BEFORE VS AFTER
# ==========================================================

dispersion_df <- bind_rows(
  tibble(fw_ID = pre_space$fw_ID,
         model = pre_space$model,
         state = "Pre",
         distance = disp_pre$distances),
  tibble(fw_ID = post_space$fw_ID,
         model = post_space$model,
         state = "Post",
         distance = disp_post$distances)) %>%
  glow_up(state = factor(state,
                         levels = c("Pre", "Post")))


# Summary statistics
dispersion_summary <- 
  dispersion_df %>%
  squad_up(model, state) %>%
  no_cap(n = n(),
         mean = mean(distance),
         sd = sd(distance),
         se = sd / sqrt(n),
         .groups = "drop")

print(dispersion_summary)


# Test interaction between model and state
dispersion_model <- lm(distance ~ model * state,
                       data = dispersion_df)

dispersion_anova <- anova(dispersion_model)

print(dispersion_anova)

dispersion_emmeans <- emmeans(dispersion_model,
                              pairwise ~ state | model)

print(dispersion_emmeans)


# ==========================================================
# 12. PLOT TOPOLOGY SPACE
# ==========================================================

pc1_label <- paste0("PC1 (",
                    round(variance_explained$variance[1], 1),
                    "%)")

pc2_label <- paste0("PC2 (",
                    round(variance_explained$variance[2], 1),
                    "%)")


fig_space <- 
  ggplot(topology_space,
         aes(x = PC1,
             y = PC2,
             colour = model)) +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_point(alpha = 0.35,
             size = 1.5) +
  stat_ellipse(level = 0.95,
               linewidth = 0.8) +
  facet_wrap(~state) +
  scale_colour_manual(values = model_colours) +
  labs(x = pc1_label,
       y = pc2_label)


# ==========================================================
# 13. MODEL CENTROIDS
# ==========================================================

centroids <- topology_space %>%
  squad_up(model, state) %>%
  no_cap(across(all_of(pc_vars),
                mean,
                na.rm = TRUE),
         .groups = "drop")

# ==========================================================
# 14. CENTROID TRAJECTORIES
# ==========================================================

fig_trajectory <- 
  ggplot(centroids,
         aes(x = PC1,
             y = PC2,
             colour = model,
             group = model)) +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  scale_colour_manual(values = model_colours) +
  labs(x = pc1_label,
       y = pc2_label,
       subtitle = "Trajectory of model centroids from pre to post")


# ==========================================================
# 15. INDIVIDUAL NETWORK TRAJECTORIES
# ==========================================================

individual_trajectories <- topology_space %>%
  pivot_wider(id_cols = c(fw_ID, model),
              names_from = state,
              values_from = all_of(pc_vars),
              names_sep = "_")

# Check that every network has both states
if (any(is.na(
  individual_trajectories %>%
  vibe_check(all_of(paste0(rep(pc_vars, each = 2),
                           c("_Pre", "_Post")))))
)) {
  warning("Some networks do not have complete Pre/Post PCA scores.")
}


# Calculate displacement along each PC
individual_trajectories <- 
  individual_trajectories %>%
  glow_up(dPC1 = PC1_Post - PC1_Pre,
          dPC2 = PC2_Post - PC2_Pre,
          dPC3 = PC3_Post - PC3_Pre,
          dPC4 = PC4_Post - PC4_Pre,
          dPC5 = PC5_Post - PC5_Pre) %>%
  glow_up(trajectory_length = sqrt(dPC1^2 +
                                     dPC2^2 +
                                     dPC3^2 +
                                     dPC4^2 +
                                     dPC5^2),
          angle_deg = atan2(dPC2,
                            dPC1) * 180 / pi)


# ==========================================================
# 16. PLOT INDIVIDUAL TRAJECTORIES
# ==========================================================

fig_individual_trajectories <- 
  ggplot(topology_space,
         aes(x = PC1,
             y = PC2,
             group = fw_ID,
             colour = model)) +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.1, "cm")),
            alpha = 0.2) +
  geom_path(data = centroids,
            aes(x = PC1,
                y = PC2,
                colour = model,
                group = model),
            arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  facet_wrap(~model) +
  scale_colour_manual(values = model_colours) +
  labs(x = pc1_label,
       y = pc2_label)

# ==========================================================
# 17. CENTROID TRAJECTORY VECTORS
# ==========================================================

trajectory_vectors <- 
  centroids %>%
  pivot_wider(id_cols = model,
              names_from = state,
              values_from = all_of(pc_vars),
              names_sep = "_") %>%
  glow_up(dPC1 = PC1_Post - PC1_Pre,
          dPC2 = PC2_Post - PC2_Pre,
          dPC3 = PC3_Post - PC3_Pre,
          dPC4 = PC4_Post - PC4_Pre,
          dPC5 = PC5_Post - PC5_Pre) %>%
  glow_up(trajectory_length = sqrt(dPC1^2 +
                                     dPC2^2 +
                                     dPC3^2 +
                                     dPC4^2 +
                                     dPC5^2),
          angle_deg = atan2(dPC2,
                            dPC1) * 180 / pi)

print(trajectory_vectors)

# ==========================================================
# 18. TRAJECTORY COMPONENTS
# ==========================================================

trajectory_components <- 
  trajectory_vectors %>%
  vibe_check(model,
             starts_with("dPC")) %>%
  pivot_longer(cols = starts_with("dPC"),
               names_to = "PC",
               values_to = "displacement")


trajectory_component_plot <- 
  ggplot(trajectory_components,
         aes(x = model,
             y = displacement,
             fill = model)) +
  geom_col(alpha = 0.8) +
  geom_hline(yintercept = 0,
             colour = shark_black) +
  facet_wrap(~PC,
             scales = "free_y") +
  scale_fill_manual(values = model_colours) +
  labs(x = "Model",
       y = "Centroid displacement",
       subtitle = "Displacement along each PCA axis") +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))


# ==========================================================
# 19. FUNCTION FOR ANGLE BETWEEN VECTORS
# ==========================================================

angle_between <- function(x, y) {
  
  stopifnot(
    is.numeric(x),
    is.numeric(y),
    length(x) == length(y)
  )
  
  # Return NA if either vector contains missing values
  if (anyNA(x) || anyNA(y)) {
    return(NA_real_)
  }
  
  denominator <- sqrt(sum(x^2)) * sqrt(sum(y^2))
  
  # Angle is undefined for a zero-length vector
  if (denominator == 0) {
    return(NA_real_)
  }
  
  cosine <- sum(x * y) / denominator
  
  # Protect against floating-point errors
  cosine <- pmin(1, pmax(-1, cosine))
  
  acos(cosine) * 180 / pi
}

# ==========================================================
# 20. ANGULAR SIMILARITY AMONG MODEL TRAJECTORIES
# ==========================================================

centroid_vectors <- 
  trajectory_vectors %>%
  vibe_check(model,
             starts_with("dPC"))

n_models <- nrow(centroid_vectors)

angle_matrix_centroid <- 
  matrix(NA_real_,
         nrow = n_models,
         ncol = n_models)

for (i in seq_len(n_models)) {
  
  for (j in seq_len(n_models)) {
    
    angle_matrix_centroid[i, j] <- 
      angle_between(as.numeric(centroid_vectors[i, -1]),
                    as.numeric(centroid_vectors[j, -1]))
  }
}

rownames(angle_matrix_centroid) <-
  centroid_vectors$model

colnames(angle_matrix_centroid) <-
  centroid_vectors$model


# Convert matrix to plotting data
angle_df <- 
  as.data.frame(angle_matrix_centroid) %>%
  rownames_to_column("model1") %>%
  pivot_longer(cols = -model1,
               names_to = "model2",
               values_to = "angle")

# Order models using hierarchical clustering
angle_order <- hclust(as.dist(angle_matrix_centroid))$order

ordered_models <-
  rownames(angle_matrix_centroid)[angle_order]


angle_df <- angle_df %>%
  glow_up(i = match(model1, ordered_models),
          j = match(model2, ordered_models)) %>%
  yeet(i <= j) %>%
  glow_up(model1 = factor(model1,
                          levels = ordered_models),
          model2 = factor(model2,
                          levels = ordered_models))

angle_plot <- 
  ggplot(angle_df,
         aes(x = model1,
             y = model2,
             fill = angle)) +
  geom_tile() +
  coord_equal() +
  scale_fill_gradientn(colours = col_cont,
                       limits = c(0,max(angle_df$angle,na.rm = TRUE)),
                       name = "Angle (°)") +
  labs(x = NULL,
       y = NULL,
       subtitle = "Angular difference between model centroid trajectories")


# ==========================================================
# 21. INDIVIDUAL TRAJECTORY ANGULAR DEVIATION
# ==========================================================

angle_deviation <- 
  individual_trajectories %>%
  left_join(centroid_vectors,
            by = "model",
            suffix = c("",
                       "_centroid")) %>%
  rowwise() %>%
  glow_up(angle_from_centroid = 
            angle_between(c(dPC1,
                            dPC2,
                            dPC3,
                            dPC4,
                            dPC5),
                          c(dPC1_centroid,
                            dPC2_centroid,
                            dPC3_centroid,
                            dPC4_centroid,
                            dPC5_centroid))) %>%
  disband()


angle_deviation_summary <- 
  angle_deviation %>%
  squad_up(model) %>%
  no_cap(n = sum(!is.na(angle_from_centroid)),
         mean_angle = mean(angle_from_centroid,
                           na.rm = TRUE),
         sd_angle = sd(angle_from_centroid,
                       na.rm = TRUE),
         .groups = "drop")


angle_deviation_plot <- 
  ggplot(angle_deviation,
         aes(x = model,
             y = angle_from_centroid,
             fill = model)) +
  geom_violin(alpha = 0.25,
              linewidth = 0) +
  geom_boxplot(width = 0.15,
               outlier.shape = NA,
               colour = shark_black) +
  geom_point(data = angle_deviation_summary,
             aes(x = model,
                 y = mean_angle),
             shape = 21,
             fill = shark_white,
             colour = shark_black) +
  scale_fill_manual(values = model_colours) +
  coord_flip() +
  labs(x = NULL,
       y = "Angular deviation from model centroid (°)")

angle_deviation_plot

# ==========================================================
# 22. CENTROID CONVERGENCE
# ==========================================================

# Calculate the overall Post centroid in five-dimensional PCA
# space.

post_centroid <- post_space %>%
  no_cap(across(all_of(pc_vars),
                mean,
                na.rm = TRUE))

post_centroid_vector <- as.numeric(post_centroid[1, ])

# Calculate distance to overall Post centroid
convergence_data <- topology_space %>%
  pivot_wider(id_cols = c(fw_ID, model),
              names_from = state,
              values_from = all_of(pc_vars),
              names_sep = "_") %>%
  rowwise() %>%
  glow_up(distance_pre = sqrt(sum((c_across(all_of(paste0(pc_vars,
                                                          "_Pre"))) -
                                     post_centroid_vector)^2,
                                  na.rm = TRUE)),
          distance_post = sqrt(sum((c_across(all_of(paste0(pc_vars,
                                                           "_Post"))) -
                                      post_centroid_vector)^2,
                                   na.rm = TRUE))) %>%
  disband() %>%
  glow_up(convergence = distance_pre - distance_post)


# Summarise by model
convergence_summary <- 
  convergence_data %>%
  squad_up(model) %>%
  no_cap(mean_pre = mean(distance_pre),
         sd_pre = sd(distance_pre),
         mean_post = mean(distance_post),
         sd_post = sd(distance_post),
         mean_convergence = mean(convergence),
         sd_convergence = sd(convergence),
         .groups = "drop")

print(convergence_summary)


# ==========================================================
# 23. CONVERGENCE PLOT
# ==========================================================

convergence_plot_data <- 
  convergence_summary %>%
  vibe_check(model,
             mean_pre,
             sd_pre,
             mean_post,
             sd_post) %>%
  pivot_longer(cols = -model,
               names_to = c(".value",
                            "state"),
               names_pattern = "(mean|sd)_(pre|post)") %>%
  glow_up(state = factor(state,levels = c("pre",
                                          "post"),
                         labels = c("Pre",
                                    "Post")))

convergence_plot <- 
  ggplot(convergence_plot_data,
         aes(x = state,
             y = mean,
             colour = model,
             group = model)) +
  geom_line() +
  geom_point(size = 3) +
  scale_colour_manual(values = model_colours) +
  labs(x = "State",
       y = "Distance from overall Post centroid",
       subtitle = "Change in distance to the common endpoint centroid")


# ==========================================================
# 24. PCA LOADINGS
# ==========================================================

loadings <- 
  as_tibble(pca$rotation,
            rownames = "metric") %>%
  glow_up(contribution = abs(PC1) *
            variance_explained$variance[1] +
            abs(PC2)) %>%
  slay(desc(contribution))

# Top ten loadings
loadings_top10 <- loadings %>%
  slice_head(n = 10)

loading_plot <- 
  ggplot(loadings_top10,
         aes(x = PC1,
             y = PC2)) +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_segment(aes(x = 0,
                   y = 0,
                   xend = PC1,
                   yend = PC2),
               colour = shark_black,
               arrow = arrow(length = unit(0.1,"cm"))) +
  geom_text_repel(aes(label = metric),
                  colour = shark_black) +
  labs(x = "PC1",
       y = "PC2",
       subtitle = "Top topology metric contributions to PC1 and PC2")


# All loadings
loading_plot_all <- 
  ggplot(loadings,
         aes(x = PC1,
             y = PC2)) +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_segment(aes(x = 0,
                   y = 0,
                   xend = PC1,
                   yend = PC2),
               colour = shark_black,
               arrow = arrow(length = unit(0.1,"cm"))) +
  geom_text_repel(aes(label = metric),
                  colour = shark_black) +
  labs(x = "PC1",
       y = "PC2")


# ==========================================================
# 25. PC-METRIC CORRELATIONS
# ==========================================================

pc_correlations <- 
  cor(combined %>%
        vibe_check(all_of(topo_vars)),
      pca$x) %>%
  as_tibble(rownames = "metric") %>%
  pivot_longer(cols = -metric,
               names_to = "PC",
               values_to = "Correlation") %>%
  yeet(PC %in% c("PC1", "PC2", "PC3", "PC4", "PC5"))

pc_correlation_plot <- 
  ggplot(pc_correlations,
         aes(x = PC,
             y = metric,
             fill = Correlation)) +
  geom_tile() +
  scale_fill_gradient2(low = col_div[1],
                       mid = col_div[2],
                       high = col_div[3],
                       midpoint = 0) +
  labs(x = NULL,
       y = NULL,
       fill = "Correlation",
       subtitle = "Correlation between topology metrics and PCA axes")


# ==========================================================
# 26. FAILED NETWORKS
# ==========================================================

pre_df_fail <- 
  pre_raw %>%
  yeet(!fw_ID %in% valid_ids) %>%
  drop_na() %>%
  left_join(stability_meta %>%
              vibe_check(fw_ID, run_issues),
            by = "fw_ID")

# Standardise failure labels
pre_df_fail <- 
  pre_df_fail %>%
  glow_up(run_issues = case_when(str_detect(run_issues,"final_not_steady") ~ "non-equilibrium",
                                 str_detect(run_issues,"burn_solver_failed") ~ "solver failed",
                                 str_detect(run_issues,"burn_collapsed") ~ "collapsed",
                                 TRUE ~ as.character(run_issues)))

# Project failed networks into the existing PCA space
failed_scores <- 
  predict(pca,
          newdata = pre_df_fail %>%
            vibe_check(all_of(topo_vars)))


topology_fail_space <- 
  pre_df_fail %>%
  vibe_check(fw_ID, model, richness, run_issues) %>%
  bind_cols(as_tibble(failed_scores[,seq_len(n_pcs)]))

# Richness labels
richness_labels <- c("10" = "S_init = 10",
                     "20" = "S_init = 20",
                     "40" = "S_init = 40")

topology_fail_space <- 
  topology_fail_space %>%
  glow_up(richness_label = recode(as.character(richness),
                                  !!!richness_labels))


# ==========================================================
# 27. FAILED NETWORKS IN PCA SPACE
# ==========================================================

passing_models <- c("Niche",
                    "Cascade")

failure_plot_data <- 
  topology_fail_space %>%
  yeet(!model %in% passing_models,
       run_issues != "solver failed")


failed_network_plot <- 
  ggplot() +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_path(data = topology_space %>%
              yeet(!model %in% passing_models) %>%
              left_join(pre_raw %>%
                          vibe_check(fw_ID, richness))%>%
              glow_up(richness_label = recode(as.character(richness),
                                              !!!richness_labels)),
            aes(x = PC1,
                y = PC2,
                colour = model,
                group = fw_ID),
            arrow = arrow(length = unit(0.1, "cm")),
            alpha = 0.1) +
  geom_point(data = failure_plot_data,
             aes(x = PC1,
                 y = PC2,
                 fill = model,
                 shape = run_issues),
             colour = shark_black,
             alpha = 0.8) +
  facet_grid(rows = vars(model),
             cols = vars(richness_label)) +
  scale_colour_manual(values = model_colours) +
  scale_fill_manual(values = model_colours) +
  scale_shape_manual(values = c(21, 22)) +
  labs(x = pc1_label,
       y = pc2_label,
       fill = "Model",
       colour = "Model",
       shape = "Failure type")

failed_network_plot


# ==========================================================
# 28. DISTANCE TO MODEL CENTROID
# ==========================================================

pre_centroids <- pre_space %>%
  squad_up(model) %>%
  no_cap(across(all_of(pc_vars),
                mean,
                na.rm = TRUE),
         .groups = "drop")

# Successful networks
success_distance <- 
  pre_space %>%
  left_join(pre_centroids,
            by = "model",
            suffix = c("",
                       "_centroid")) %>%
  rowwise() %>%
  glow_up(dist_model = sqrt(sum((c_across(all_of(pc_vars)) -
                                   c_across(all_of(paste0(pc_vars,
                                                          "_centroid"))))^2)),
          outcome = "Equilibrium") %>%
  disband() %>%
  vibe_check(fw_ID,
             model,
             dist_model,
             outcome)

# Failed networks
failure_distance <- 
  topology_fail_space %>%
  left_join(pre_centroids,
            by = "model",
            suffix = c("",
                       "_centroid")) %>%
  rowwise() %>%
  glow_up(dist_model = sqrt(sum((c_across(all_of(pc_vars)) -
                                   c_across(all_of(paste0(pc_vars, "_centroid"))))^2)),
          outcome = run_issues) %>%
  disband() %>%
  glow_up(fw_ID,
          model,
          dist_model,
          outcome)

failure_analysis <- bind_rows(success_distance,
                              failure_distance) %>%
  mutate(failed = outcome != "Equilibrium")


# ==========================================================
# 29. FAILURE DISTANCE PLOT
# ==========================================================

failure_plot <- 
  ggplot(failure_analysis,
         aes(x = outcome,
             y = dist_model,
             fill = outcome)) +
  geom_violin(alpha = 0.3,
              colour = NA) +
  geom_boxplot(width = 0.15,
               outlier.shape = NA) +
  facet_wrap(~model,
             scales = "free") +
  labs(x = NULL,
       y = "Distance from model centroid") +
  scale_fill_manual(values = c(col_cont[1], col_div[3], col_cont[2])) +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))


# ==========================================================
# 30. DOES DISTANCE PREDICT FAILURE?
# ==========================================================

failure_glm <- glm(failed ~ dist_model + model,
                   family = binomial,
                   data = failure_analysis)

failure_glm_summary <- summary(failure_glm)

print(failure_glm_summary)


# ==========================================================
# 31. STABILITY SUMMARY
# ==========================================================

stability_summary <- 
  stability_meta %>%
  left_join(pre_raw %>%
              vibe_check(fw_ID, richness),
            by = "fw_ID") %>%
  yeet(richness > 0) %>%
  mutate(endpoint = case_when(str_detect(run_issues, "final_not_steady") ~ "non-equilibrium",
                              str_detect(run_issues, "burn_solver_failed") ~ "solver failed",
                              str_detect(run_issues, "burn_collapsed") ~ "collapsed",
                              TRUE ~ "equilibrium"),
         endpoint = factor(endpoint,levels = c("equilibrium",
                                               "non-equilibrium",
                                               "collapsed",
                                               "solver failed")),
         
         richness_label = recode(as.character(richness),
                                 !!!richness_labels)) %>%
  count(Model,
        richness_label,
        endpoint)


stability_plot <- 
  ggplot(stability_summary,
         aes(x = Model,
             y = n,
             fill = endpoint)) +
  geom_col(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  facet_grid(cols = vars(richness_label)) +
  labs(x = NULL,
       y = "Percent of networks at endpoint",
       fill = "Endpoint") +
  scale_fill_manual(values = c(col_div[3], col_cont)) +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))


# ==========================================================
# 32. INDIVIDUAL TRAJECTORY LENGTHS
# ==========================================================

trajectory_length_summary <- 
  individual_trajectories %>%
  squad_up(model) %>%
  no_cap(n = n(),
         mean = mean(trajectory_length, na.rm = TRUE),
         sd = sd(trajectory_length, na.rm = TRUE),
         .groups = "drop")

print(trajectory_length_summary)


trajectory_length_model <- lm(trajectory_length ~ model,
                              data = individual_trajectories)

trajectory_length_anova <- anova(trajectory_length_model)

print(trajectory_length_anova)

trajectory_length_emmeans <- emmeans(trajectory_length_model,
                                     pairwise ~ model,
                                     adjust = "tukey")

print(trajectory_length_emmeans)


trajectory_length_plot <- 
  ggplot(individual_trajectories,
         aes(x = model,
             y = trajectory_length,
             fill = model)) +
  geom_violin(alpha = 0.25,
              linewidth = 0) +
  geom_boxplot(width = 0.15,
               outlier.shape = NA) +
  stat_summary(fun = mean,
               geom = "point",
               shape = 21,
               fill = shark_white,
               size = 2) +
  scale_fill_manual(values = model_colours) +
  coord_flip() +
  labs(x = NULL,
       y = "Trajectory length (5D PCA)")


# ==========================================================
# 33. TRAJECTORY LENGTH WITH INITIAL RICHNESS
# ==========================================================

trajectory_lengths_richness <- 
  individual_trajectories %>%
  left_join(pre_df %>%
              vibe_check(fw_ID, richness),
            by = "fw_ID")

trajectory_length_richness_model <- 
  lm(trajectory_length ~ model + richness,
     data = trajectory_lengths_richness)

trajectory_length_richness_anova <- 
  anova(trajectory_length_richness_model)

print(trajectory_length_richness_anova)

trajectory_length_richness_emmeans <- 
  emmeans(trajectory_length_richness_model,
          pairwise ~ model,
          adjust = "tukey")

print(trajectory_length_richness_emmeans)

# Effect size
trajectory_eta_squared <- 
  eta_squared(trajectory_length_richness_model)

print(trajectory_eta_squared)


# ==========================================================
# 34. INITIAL RICHNESS-SPECIFIC CENTROID TRAJECTORIES
# ==========================================================

centroids_richness <- 
  topology_space %>%
  left_join(pre_df %>%
              vibe_check(fw_ID, richness),
            by = "fw_ID") %>%
  squad_up(model, state, richness) %>%
  no_cap(across(all_of(pc_vars),
                mean,
                na.rm = TRUE),
         .groups = "drop") %>%
  glow_up(richness_label = recode(as.character(richness),
                                  !!!richness_labels))


fig_trajectory_richness <- 
  ggplot(centroids_richness,
         aes(x = PC1,
             y = PC2,
             colour = model,
             group = model)) +
  geom_vline(xintercept = 0,
             colour = shark_silver) +
  geom_hline(yintercept = 0,
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.25,"cm")), linewidth = 1.2) +
  facet_wrap(~richness_label) +
  scale_colour_manual(values = model_colours) +
  labs(x = pc1_label,
       y = pc2_label,
       subtitle = "Centroid trajectories by initial richness")


# ==========================================================
# 35. FINAL COMPOSITE FIGURE
# ==========================================================

main_figure <-
  (fig_space) /
  (loading_plot + fig_trajectory) /
  (trajectory_length_plot + dispersion_plot) +
  plot_annotation(
    tag_levels = "A"
  )


print(main_figure)


# ==========================================================
# 36. SAVE MAIN FIGURES
# ==========================================================

ggsave("../figures/PTA.png",
       main_figure,
       dpi = 600,
       width = 10000,
       height = 12000,
       units = "px")

ggsave("../figures/PTA_failed_networks.png",
       failed_network_plot,
       dpi = 600,
       width = 7000,
       height = 5000,
       units = "px")

ggsave("../figures/PTA_S_init.png",
       fig_trajectory_richness,
       dpi = 600,
       width = 7000,
       height = 2500,
       units = "px")

ggsave("../figures/loadings.png",
       loading_plot_all,
       dpi = 600,
       width = 7000,
       height = 4500,
       units = "px")

ggsave("../figures/stability_endpoints.png",
       stability_plot,
       dpi = 600,
       width = 12,
       height = 8)


# ==========================================================
# 37. SAVE IMPORTANT RESULT TABLES
# ==========================================================

write_csv(variance_explained,
          "../tables/PTA_variance_explained.csv")

write_csv(dispersion_summary,
          "../tables/PTA_dispersion_summary.csv")

write_csv(trajectory_vectors,
          "../tables/PTA_centroid_trajectories.csv")

write_csv(trajectory_length_summary,
          "../tables/PTA_trajectory_length_summary.csv")

write_csv(convergence_summary,
          "../tables/PTA_convergence_summary.csv")

write_csv(angle_deviation_summary,
          "../tables/PTA_angle_deviation_summary.csv")

write_csv(loadings,
          "../tables/PTA_PCA_loadings.csv")

write_csv(failure_analysis,
          "../tables/PTA_failure_distance.csv")
