############################################################
# TOPOLOGY SPACE TRANSFORMATION ANALYSIS
#
# Goal:
# Quantify how ecological dynamics transform the
# topology space generated by different food-web
# reconstruction frameworks.
############################################################

#------1. Load libraries -------------------------------------------------------

library(tidyverse)
library(vegan)
library(emmeans)
library(patchwork)
library(ggrepel)
library(genzplyr)
library(geomorph)
library(circular)
library(RVAideMemoire)
library(vegan)
library(tidytext)

source("lib/plotting_theme.R")

set.seed(66)

#------2. Load data ------------------------------------------------------------

pre_df <-
  read_csv("outputs/topology_initial.csv") %>%
  na.omit()

post_df <-
  read_csv("outputs/topology_END.csv") %>%
  yeet(!is.na(richness)) %>%
  yeet(richness > 0) %>%
  na.omit()


stability_meta <- read_csv("outputs/stability_metrics.csv", show_col_types = FALSE) %>%
  mutate(Model = factor(Model, levels = model_order))

# keep only stable networks
valid_ids <- stability_meta %>%
  yeet(run_issues == "success") %>%
  main_character(fw_ID)

pre_df <-
  pre_df %>%
  yeet(fw_ID %in% valid_ids)

post_df <-
  post_df %>%
  yeet(fw_ID %in% valid_ids)

# combine
combined <-
  bind_rows(
    pre_df %>%
      mutate(state = "Pre"),
    post_df %>%
      mutate(state = "Post")
  )

# define topo vars
topo_vars <-
  combined %>%
  vibe_check(-fw_ID, -model, -state) %>%
  names()

#------4. PCA ------------------------------------------------------------------

pca <- prcomp(combined[, topo_vars],
              center = TRUE,
              scale. = TRUE)

scores <- as.data.frame(pca$x[,1:5])

topology_space <- bind_cols(combined[,c("fw_ID","model","state")],
                            scores) %>%
  glow_up(state = factor(state, levels = c("Pre", "Post")))

#------5. PERMANOVA ------------------------------------------------------------

# subset pre state and run PERMANOVA
pre_space <- topology_space %>%
  yeet(state == "Pre")
pre_dist  <- vegdist(pre_space[, c("PC1", "PC2", "PC3", "PC4", "PC5")], 
                     method = "euclidean")

permanova_pre <- adonis2(pre_dist ~ model, data = pre_space, permutations = 999)
print(permanova_pre)

# Subset post state and run PERMANOVA
post_space <- topology_space %>% 
  yeet(state == "Post")
post_dist  <- vegdist(post_space[, c("PC1", "PC2", "PC3", "PC4", "PC5")], 
                      method = "euclidean")

permanova_post <- adonis2(post_dist ~ model, data = post_space, permutations = 999)
print(permanova_post)

library(pairwiseAdonis)

# Pairwise comparisons for Pre state
pairwise_pre <- pairwise.adonis2(pre_dist ~ model, data = pre_space, p.adjust.m = "bonferroni")
print(pairwise_pre)

# Pairwise comparisons for Post state
pairwise_post <- pairwise.adonis2(post_dist ~ model, data = post_space, p.adjust.m = "bonferroni")
print(pairwise_post)

# Check group dispersions for Pre state
disp_pre <- betadisper(pre_dist, pre_space$model)
tukey_pre <- TukeyHSD(disp_pre)
print(tukey_pre)

# Check group dispersions for Post state
disp_post <- betadisper(post_dist, post_space$model)
tukey_post <- TukeyHSD(disp_post)
print(tukey_post)

# Plot to visualize centroids and dispersion
plot(disp_pre)
plot(disp_post)

#------6. Variance expalined ---------------------------------------------------

variance_explained <-
  tibble(
    PC = seq_along(pca$sdev),
    variance =
      100 *
      pca$sdev^2 /
      sum(pca$sdev^2)
  )

variance_explained

# FIGURE 1
# common topo space

fig_space <-
  ggplot(topology_space,
         aes(x = PC1,
             y = PC2,
             colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_point(alpha = 0.35,
             size = 1.5) +
  stat_ellipse(level = 0.95,
               linewidth = 0.8) +
  facet_wrap(vars(state)) +
  scale_colour_manual(values = model_colours) +
  labs(x = glue::glue("PC1 ({round(variance_explained$variance[1],1)}%)"),
       y = glue::glue("PC2 ({round(variance_explained$variance[2],1)}%)"))

fig_space

############################################################
# CENTROID TRAJECTORIES
############################################################

centroids <-
  topology_space %>%
  squad_up(model, state) %>%
  summarise(
    across(starts_with("PC"), mean),
    .groups = "drop"
  )

fig_traj <-
  ggplot(centroids,
         aes(x = PC1,
             y = PC2,
             colour = model,
             group = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  scale_colour_manual(values = model_colours) +
  labs(x = glue::glue("PC1 ({round(variance_explained$variance[1],1)}%)"),
       y = glue::glue("PC2 ({round(variance_explained$variance[2],1)}%)"),
       subtitle = "Trajectory of networks from pre to post, using centroid")

fig_traj

replicate_paths <-
  topology_space %>%
  arrange(fw_ID, state)

ggplot(replicate_paths,
       aes(x = PC1,
           y = PC2,
           group = fw_ID,
           colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.1, "cm")),
            alpha = 0.2) +
  geom_path(data = centroids,
            aes(x = PC1,
                y = PC2,
                colour = model,
                group = model),
            arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  facet_wrap(vars(model)) +
  scale_colour_manual(values = model_colours)

############################################################
# 10. TRAJECTORY VECTORS
############################################################

trajectory_vectors <-
  centroids %>%
  pivot_wider(
    names_from = state,
    values_from = starts_with("PC")
  ) %>%
  mutate(dPC1 = PC1_Post - PC1_Pre,
         dPC2 = PC2_Post - PC2_Pre,
         dPC3 = PC3_Post - PC3_Pre,
         dPC4 = PC4_Post - PC4_Pre,
         dPC5 = PC5_Post - PC5_Pre,
         trajectory_length = sqrt(dPC1^2 +
                                    dPC2^2 +
                                    dPC3^2 +
                                    dPC4^2 +
                                    dPC5^2),
         angle_deg = atan2(dPC2, dPC1) * 180 / pi)

trajectory_vectors %>%
  vibe_check(model, dPC1, dPC2, dPC3, dPC4, dPC5) %>%
  pivot_longer(-model) %>%
  squad_up(model) %>%
  no_cap(abs_disp = sum(abs(value))) %>%
  slay(desc(abs_disp))

trajectory_vectors %>%
  vibe_check(model, dPC1, dPC2, dPC3, dPC4, dPC5) %>%
  slay(desc(abs(dPC1)))


disp_plot <-
  trajectory_vectors %>%
  vibe_check(model, dPC1, dPC2, dPC3, dPC4, dPC5) %>%
  pivot_longer(-model) %>%
  squad_up(model) %>%
  glow_up(col_colour = if_else(abs(value) == max(abs(value)),
                               shark_black,
                               NA),
          fill_col = model_colours[model]) %>%
  disband() %>%
  glow_up(model = reorder_within(model, -abs(value), name)) %>%
  ggplot() +
  geom_col(aes(y = value,
               x = model,
               fill = fill_col,
               colour = col_colour),
           alpha = 0.8) +
  geom_hline(yintercept = 0,
             colour = shark_black) +
  facet_wrap(vars(name), 
             scales = "free_x") +
  scale_x_reordered() +
  scale_fill_identity() +
  scale_colour_identity() +
  labs(
    y = "Displacement of centroid along PC axis",
    x = "Model",
    subtitle = "Black bounding box denotes axis with largest absolute displacement"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

disp_plot

############################################################
# 11. COSINE SIMILARITY AMONG MODELS
############################################################

traj_mat_indiv_nets <-
  topology_space %>%
  pivot_wider(
    names_from = state,
    values_from = starts_with("PC")
  ) %>%
  mutate(dPC1 = PC1_Post - PC1_Pre,
         dPC2 = PC2_Post - PC2_Pre,
         dPC3 = PC3_Post - PC3_Pre,
         dPC4 = PC4_Post - PC4_Pre,
         dPC5 = PC5_Post - PC5_Pre,
         trajectory_length = sqrt(dPC1^2 +
                                    dPC2^2 +
                                    dPC3^2 +
                                    dPC4^2 +
                                    dPC5^2))

angle_between <- function(v1, v2) {
  
  cos_theta <- sum(v1 * v2) /
    (sqrt(sum(v1^2)) * sqrt(sum(v2^2)))
  
  # avoid numerical issues
  cos_theta <- pmin(1, pmax(-1, cos_theta))
  
  acos(cos_theta) * 180 / pi
}

# each indiv network
traj_mat_indiv <- as.matrix(
  traj_mat_indiv_nets %>%
    vibe_check(starts_with("dPC"))
)

n <- nrow(traj_mat_indiv_nets)

angle_mat <- matrix(NA, n, n)

for(i in seq_len(n)){
  for(j in seq_len(n)){
    angle_mat[i,j] <- angle_between(
      traj_mat_indiv[i,],
      traj_mat_indiv[j,]
    )
  }
}

rownames(angle_mat) <- traj_mat_indiv_nets$fw_ID
colnames(angle_mat) <- traj_mat_indiv_nets$fw_ID

# working from centroids
traj_mat_cent <- as.matrix(
  trajectory_vectors %>%
    vibe_check(starts_with("dPC"))
)

n <- nrow(trajectory_vectors)

angle_mat <- matrix(NA, n, n)

for(i in seq_len(n)){
  for(j in seq_len(n)){
    angle_mat[i,j] <- angle_between(
      traj_mat_cent[i,],
      traj_mat_cent[j,]
    )
  }
}

rownames(angle_mat) <- trajectory_vectors$model
colnames(angle_mat) <- trajectory_vectors$model

angle_df <- 
  as.data.frame(angle_mat) %>%
  rownames_to_column("model1") %>%
  pivot_longer(-model1,
               names_to = "model2",
               values_to = "angle") 

ord <- hclust(as.dist(angle_mat))$order

mods <- rownames(angle_mat)[ord]

angle_df <- angle_df %>%
  squad_up(i = match(model1, mods),
           j = match(model2, mods)) %>%
  yeet(i <= j) %>%   # lower triangle + diagonal
  vibe_check(-i, -j) %>%
  squad_up(model1 = factor(model1, levels = mods),
           model2 = factor(model2, levels = mods))

ggplot(angle_df,
       aes(x = model1,
           y = model2,
           fill = angle)) +
  geom_tile() +
  coord_equal() +
  scale_fill_gradientn(
    colours = col_cont,
    limits = c(0, max(angle_df$angle)),
    name = "Angle (°)"
  ) +
  labs(x = NULL,
       y = NULL,
       subtitle = "Angle of change between pre and post, centroids")

############################################################
# CENTROID CONVERGENCE
############################################################

post_centroid <- traj_mat_indiv_nets %>%
  no_cap(across(matches("PC[0-9]+_Post"), mean))

post_centroid_vec <- as.numeric(post_centroid)

dist_to_post <- traj_mat_indiv_nets %>%
  rowwise() %>%
  glow_up(dist_pre = sqrt(sum((c_across(matches("PC[0-9]+_Pre")) -
                                 post_centroid_vec)^2)),
          dist_post = sqrt(sum((c_across(matches("PC[0-9]+_Post")) -
                                  post_centroid_vec)^2))) %>%
  disband() %>%
  glow_up(convergence = dist_pre - dist_post)

model_conv <- dist_to_post %>%
  squad_up(model) %>%
  no_cap(mean_pre = mean(dist_pre),
         sd_pre = sd(dist_pre),
         mean_post = mean(dist_post),
         sd_post = sd(dist_post),
         mean_convergence = mean(convergence),
         sd_convergence = sd(convergence))

plot_df <- model_conv %>%
  vibe_check(model,
             mean_pre,
             sd_pre,
             mean_post,
             sd_post) %>%
  pivot_longer(-model,
               names_to = c(".value", "state"),
               names_pattern = "(mean|sd)_(pre|post)") %>%
  glow_up(state = factor(str_remove(state, "dist_"),
                         levels = c("pre", "post")))

dist_plot <- 
  ggplot(plot_df,
         aes(state,
             mean,
             colour = model,
             group = model)) +
  geom_line() +
  geom_point(size = 3) +
  #geom_errorbar(
  #  aes(
  #    ymin = mean - sd,
  #    ymax = mean + sd
  #  ),
  #  width = 0.05
  #) +
  #facet_wrap(vars(model)) +
  scale_colour_manual(values = model_colours) +
  labs(x = "State",
       y = "Distance from centroid",
       subtitle = "Showing distance (5D space) from the combined centroid for each state")

## LOADINGS

loadings_df <-
  as_tibble(pca$rotation,
            rownames = "metric")  %>%
  glow_up(contribution = abs(PC1) * variance_explained$variance[1] +
            abs(PC2) * variance_explained$variance[2]) %>%
  slay(desc(contribution)) %>%
  slice_head(n = 10)

loading_plot <-
  ggplot(loadings_df) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_segment(aes(x = 0,
                   y = 0,
                   xend = PC1,
                   yend = PC2),
               colour = shark_black,
               arrow = arrow(length = unit(0.1, "cm"))) +
  geom_text_repel(aes(x = PC1,
                      y = PC2,
                      label = metric),
                  colour = shark_black) +
  labs(x = "PC1",
       y = "PC2",
       subtitle = "Metric loadings with PC axis")

# let plot and save ALL loadings as well

loadings_all <-
  as_tibble(pca$rotation,
            rownames = "metric")  %>%
  glow_up(contribution = abs(PC1) * variance_explained$variance[1] +
            abs(PC2) * variance_explained$variance[2])

ggplot(loadings_all) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_segment(aes(x = 0,
                   y = 0,
                   xend = PC1,
                   yend = PC2),
               colour = shark_black,
               arrow = arrow(length = unit(0.1, "cm"))) +
  geom_text_repel(aes(x = PC1,
                      y = PC2,
                      label = metric),
                  colour = shark_black) +
  labs(x = "PC1",
       y = "PC2")

ggsave("../figures/loadings.png",
       dpi = 600,
       height = 4500,
       width = 7000,
       units = "px")

scores <- pca$x[, 1:5]

pc_cor <- cor(combined[, topo_vars],
              scores) %>%
  as_tibble(rownames = "metric") %>%
  pivot_longer(-metric,
               names_to = "PC",
               values_to = "Correlation") 

met_corr <- 
  ggplot(pc_cor,
         aes(PC, metric, 
             fill = Correlation)) +
  geom_tile() +
  scale_fill_gradient2(
    low = col_div[1],
    mid = col_div[2],
    high = col_div[3],
    midpoint = 0
  ) +
  labs(x = NULL,
       y = NULL,
       subtitle = "Metric correlation with PC axis")


combo_plot <-
  (fig_space) / (loading_plot + fig_traj) / 
  (disp_plot + theme(legend.position = "none") + dist_plot) +
  plot_annotation(tag_levels = 'A')

combo_plot

ggsave("../figures/PTA.png",
       combo_plot,
       dpi = 600,
       width = 10000,
       height = 12000,
       units = "px")


############################################################
# BONUS FIGURES
############################################################

centroids_rich <-
  topology_space %>%
  left_join(pre_df %>%
              vibe_check(fw_ID, richness)) %>%
  squad_up(model, state, richness) %>%
  summarise(across(starts_with("PC"), mean),
            .groups = "drop") %>%
  glow_up(richness = case_when(richness == 10 ~ "S_init = 10",
                               richness == 40 ~ "S_init = 40",
                               richness == 20 ~ "S_init = 20"))

fig_traj <-
  ggplot(centroids_rich,
         aes(x = PC1,
             y = PC2,
             colour = model,
             group = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  facet_grid(row = ~richness) +
  scale_colour_manual(values = model_colours) +
  labs(x = glue::glue("PC1 ({round(variance_explained$variance[1],1)}%)"),
       y = glue::glue("PC2 ({round(variance_explained$variance[2],1)}%)"),
       subtitle = "Trajectory of networks from pre to post, using centroid")

fig_traj

replicate_paths_rich <-
  topology_space %>%
  left_join(pre_df %>%
              vibe_check(fw_ID, richness))  %>%
  glow_up(richness = case_when(richness == 10 ~ "S_init = 10",
                               richness == 40 ~ "S_init = 40",
                               richness == 20 ~ "S_init = 20"))

ggplot(replicate_paths_rich,
       aes(x = PC1,
           y = PC2,
           group = fw_ID,
           colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.1, "cm")),
            alpha = 0.2) +
  geom_path(data = centroids_rich,
            aes(x = PC1,
                y = PC2,
                colour = model,
                group = model),
            arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  facet_grid(cols = vars(richness),
             rows = vars(model)) +
  scale_colour_manual(values = model_colours) +
  theme(legend.position = 'none')

ggsave("../figures/PTA_S_init.png",
       dpi = 600,
       width = 7000,
       height = 5000,
       units = "px")

# project 'fail' networks into PCA space

pre_df_fail <-
  read_csv("outputs/topology_initial.csv") %>%
  yeet(!fw_ID %in% valid_ids) %>%
  na.omit() %>%
  left_join(stability_meta %>%
              vibe_check(fw_ID, run_issues) %>%
              glow_up(run_issues = case_when(str_detect(run_issues, "final_not_steady") ~ "final_not_steady",
                                             str_detect(run_issues, "burn_solver_failed") ~ "burn_solver_failed",
                                             str_detect(run_issues, "	burn_collapsed") ~ "	burn_collapsed",
                                             .default = as.character(run_issues))))


new_scores <- predict(pca, 
                      newdata = pre_df_fail[, topo_vars])

topology_fail_space <- bind_cols(pre_df_fail[,c("fw_ID","model", "richness", "run_issues")],
                                 new_scores)  %>%
  glow_up(richness = case_when(richness == 10 ~ "S_init = 10",
                               richness == 40 ~ "S_init = 40",
                               richness == 20 ~ "S_init = 20"))%>%
  glow_up(run_issues = case_when(str_detect(run_issues, "final_not_steady") ~ "non-equilibrium",
                                 str_detect(run_issues, "burn_solver_failed") ~ "solver failed",
                                 str_detect(run_issues, "burn_collapsed") ~ "collapsed",
                                 .default = as.character("equilibrium"))) %>%
  disband() %>%
  yeet(run_issues != "solver failed") %>%
  yeet(!model %in% c("Niche", "Cascade"))

ggplot(replicate_paths_rich %>%
         yeet(!model %in% c("Niche", "Cascade")),
       aes(x = PC1,
           y = PC2,
           group = fw_ID,
           colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.1, "cm")),
            alpha = 0.1) +
  geom_path(data = centroids %>%
              yeet(!model %in% c("Niche", "Cascade")),
            aes(x = PC1,
                y = PC2,
                colour = model,
                group = model),
            arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  geom_point(data = topology_fail_space,
             aes(x = PC1,
                 y = PC2,
                 fill = model,
                 shape = run_issues),
             colour = shark_black,
             alpha = 0.8) +
  facet_grid(rows = vars(model),
             cols = vars(richness)) +
  scale_colour_manual(values = model_colours) +
  scale_shape_manual(values = c(21, 22, 24)) +
  scale_fill_manual(values = model_colours) +
  theme(legend.position = 'right')

ggsave("../figures/PTA_failed_networks.png",
       dpi = 600,
       width = 7000,
       height = 5000,
       units = "px")

# failed points but relative to pre centroids

hulls <- topology_space %>%
  group_by(model, state) %>%
  slice(chull(PC1, PC2)) %>%
  ungroup() %>%
  yeet(state == "Pre")

# keep full pca space
ggplot(topology_space %>%
         yeet(state == "Pre"),
       aes(x = PC1,
           y = PC2,
           colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_point(alpha = 0.2,
             size = 1.5) +
  # plot only pre state ellipse
  geom_polygon(data = hulls, 
               aes(x = PC1, 
                   y = PC2, 
                   group = model, 
                   colour = model),
               alpha = 0.2, fill = NA) +
  # we know MaxEnt and Random are extreme so we will drop them
  # for the failed networks
  geom_point(data = topology_fail_space %>%
               yeet(model != "Random") %>%
               yeet(model != "MaxEnt"),
             aes(x = PC1,
                 y = PC2,
                 fill = model,
                 shape = run_issues),
             colour = shark_black) +
  scale_colour_manual(values = model_colours) +
  scale_shape_manual(values = c(21, 22, 24)) +
  scale_fill_manual(values = model_colours)

topology_fail_space %>%
  yeet(model != "Random") %>%
  yeet(model != "MaxEnt") %>%
  squad_up(model) %>%
  no_cap(
    across(starts_with("PC"), mean),
    .groups = "drop"
  ) %>%
  pivot_longer(-model, names_to = "name", values_to = "value") %>%
  squad_up(model) %>%
  slice_max(abs(value), n = 1, with_ties = FALSE)

# love a good boxplot

read_csv("outputs/topology_initial.csv") %>%
  pivot_longer(-c(model, fw_ID)) %>%
  ggplot() +
  geom_boxplot(aes(x = model,
                   y = value,
                   colour = model)) +
  facet_wrap(vars(name),
             scales = "free_y") +
  scale_colour_manual(values = model_colours) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
stability_meta %>%
  left_join(read_csv("outputs/topology_initial.csv") %>%
              vibe_check(fw_ID, richness)) %>%
  yeet(richness > 0) %>%
  glow_up(run_issues = case_when(str_detect(run_issues, "final_not_steady") ~ "non-equilibrium",
                                 str_detect(run_issues, "burn_solver_failed") ~ "solver failed",
                                 str_detect(run_issues, "burn_collapsed") ~ "collapsed",
                                 .default = as.character("equilibrium"))) %>%
  squad_up(Model, run_issues, richness) %>%
  tally() %>%
  glow_up(run_issues = factor(run_issues,
                              levels = c("equilibrium", "non-equilibrium",
                                         "collapsed", "solver failed")),
          fill_col = case_when(run_issues == "non-equilibrium" ~ col_cont[3],
                               run_issues == "solver failed" ~ col_cont[2],
                               run_issues == "collapsed" ~ col_cont[1],
                               .default = as.character(col_div[3])),
          richness = case_when(richness == 10 ~ "S_init = 10",
                               richness == 40 ~ "S_init = 40",
                               richness == 20 ~ "S_init = 20")) %>%
  ggplot(aes(x = Model, 
             y = n, 
             fill = run_issues)) +
  geom_col(position = "fill") +
  scale_fill_manual(values = c(col_div[3], col_cont)) +
  scale_y_continuous(labels = scales::percent)+
  facet_grid(cols = vars(richness)) +
  labs(y = "Percent of networks at endpoint",
       x = NULL,
       fill = "Endpoint") +
  theme(axis.text.x = element_text(hjust = 1, angle = 45))

ggsave("../figures/stability_enpoints.png",
       width = 12, 
       height = 8, 
       dpi = 600)

