############################################################
# TOPOLOGY SPACE TRANSFORMATION ANALYSIS
#
# Goal:
# Quantify how ecological dynamics transform the
# topology space generated by different food-web
# reconstruction frameworks.
############################################################

#------1. Load libraries -------------------------------------------------------

library(tidyverse)
library(vegan)
library(emmeans)
library(patchwork)
library(ggrepel)
library(genzplyr)
library(geomorph)
library(circular)
library(RVAideMemoire)
library(vegan)
library(tidytext)

source("lib/plotting_theme.R")

set.seed(66)

#------2. Load data ------------------------------------------------------------

pre_df <-
  read_csv("outputs/topology_initial.csv") %>%
  na.omit()

post_df <-
  read_csv("outputs/topology_END.csv") %>%
  yeet(!is.na(richness)) %>%
  yeet(richness > 0) %>%
  na.omit()

# keep only matched networks
valid_ids <- intersect(pre_df$fw_ID, post_df$fw_ID)

pre_df <-
  pre_df %>%
  yeet(fw_ID %in% valid_ids)

post_df <-
  post_df %>%
  yeet(fw_ID %in% valid_ids)

# combine
combined <-
  bind_rows(
    pre_df %>%
      mutate(state = "Pre"),
    post_df %>%
      mutate(state = "Post")
  )

# define topo vars
topo_vars <-
  combined %>%
  vibe_check(-fw_ID, -model, -state) %>%
  names()

#------3. Standardise Metrics --------------------------------------------------

X <- scale(combined[, topo_vars])

#------4. PCA ------------------------------------------------------------------

pca <- prcomp(X,
              center = FALSE,
              scale. = FALSE)

scores <- as.data.frame(pca$x[,1:5])

topology_space <- bind_cols(combined[,c("fw_ID","model","state")],
                            scores) %>%
  glow_up(state = factor(state, levels = c("Pre", "Post")))

#------5. PERMANOVA ------------------------------------------------------------

# subset pre state and run PERMANOVA
pre_space <- topology_space %>%
  yeet(state == "Pre")
pre_dist  <- vegdist(pre_space[, c("PC1", "PC2", "PC3", "PC4", "PC5")], 
                     method = "euclidean")

permanova_pre <- adonis2(pre_dist ~ model, data = pre_space, permutations = 999)
print(permanova_pre)

# Subset post state and run PERMANOVA
post_space <- topology_space %>% 
  yeet(state == "Post")
post_dist  <- vegdist(post_space[, c("PC1", "PC2", "PC3", "PC4", "PC5")], 
                      method = "euclidean")

permanova_post <- adonis2(post_dist ~ model, data = post_space, permutations = 999)
print(permanova_post)

#------6. Variance expalined ---------------------------------------------------

variance_explained <-
  tibble(
    PC = seq_along(pca$sdev),
    variance =
      100 *
      pca$sdev^2 /
      sum(pca$sdev^2)
  )

variance_explained

# FIGURE 1
# common topo space

fig_space <-
  ggplot(topology_space,
         aes(x = PC1,
             y = PC2,
             colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_point(alpha = 0.35,
             size = 1.5) +
  stat_ellipse(level = 0.95,
               linewidth = 0.8) +
  facet_wrap(vars(state)) +
  scale_colour_manual(values = model_colours) +
  labs(x = glue::glue("PC1 ({round(variance_explained$variance[1],1)}%)"),
       y = glue::glue("PC2 ({round(variance_explained$variance[2],1)}%)")) +
  figure_theme

fig_space

############################################################
# CENTROID TRAJECTORIES
############################################################

centroids <-
  topology_space %>%
  squad_up(model, state) %>%
  summarise(
    across(starts_with("PC"), mean),
    .groups = "drop"
  )

fig_traj <-
  ggplot(centroids,
         aes(x = PC1,
             y = PC2,
             colour = model,
             group = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  scale_colour_manual(values = model_colours) +
  labs(x = glue::glue("PC1 ({round(variance_explained$variance[1],1)}%)"),
       y = glue::glue("PC2 ({round(variance_explained$variance[2],1)}%)"),
       subtitle = "Trajectory of networks from pre to post, using centroid") +
  figure_theme

fig_traj

replicate_paths <-
  topology_space %>%
  arrange(fw_ID, state)

ggplot(replicate_paths,
       aes(x = PC1,
           y = PC2,
           group = fw_ID,
           colour = model)) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_path(arrow = arrow(length = unit(0.1, "cm")),
            alpha = 0.2) +
  geom_path(data = centroids,
            aes(x = PC1,
                y = PC2,
                colour = model,
                group = model),
            arrow = arrow(length = unit(0.25, "cm")),
            linewidth = 1.2) +
  facet_wrap(vars(model)) +
  scale_colour_manual(values = model_colours) +
  figure_theme

############################################################
# 10. TRAJECTORY VECTORS
############################################################

trajectory_vectors <-
  centroids %>%
  pivot_wider(
    names_from = state,
    values_from = starts_with("PC")
  ) %>%
  mutate(dPC1 = PC1_Post - PC1_Pre,
         dPC2 = PC2_Post - PC2_Pre,
         dPC3 = PC3_Post - PC3_Pre,
         dPC4 = PC4_Post - PC4_Pre,
         dPC5 = PC5_Post - PC5_Pre,
         trajectory_length = sqrt(dPC1^2 +
                                    dPC2^2 +
                                    dPC3^2 +
                                    dPC4^2 +
                                    dPC5^2),
         angle_deg = atan2(dPC2, dPC1) * 180 / pi)

disp_plot <-
  trajectory_vectors %>%
  vibe_check(model, dPC1, dPC2, dPC3, dPC4, dPC5) %>%
  pivot_longer(-model) %>%
  squad_up(model) %>%
  glow_up(col_colour = if_else(abs(value) == max(abs(value)),
                               shark_black,
                               NA),
          fill_col = model_colours[model]) %>%
  disband() %>%
  glow_up(model = reorder_within(model, -abs(value), name)) %>%
  ggplot() +
  geom_col(aes(y = value,
               x = model,
               fill = fill_col,
               colour = col_colour),
           alpha = 0.8) +
  geom_hline(yintercept = 0,
             colour = shark_black) +
  facet_wrap(vars(name), 
             scales = "free_x") +
  scale_x_reordered() +
  scale_fill_identity() +
  scale_colour_identity() +
  labs(
    y = "Displacement of centroid along PC axis",
    x = "Model",
    subtitle = "Black bounding box denotes axis with largest absolute displacement"
  ) +
  figure_theme +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

disp_plot

############################################################
# 11. COSINE SIMILARITY AMONG MODELS
############################################################

traj_mat_indiv_nets <-
  topology_space %>%
  pivot_wider(
    names_from = state,
    values_from = starts_with("PC")
  ) %>%
  mutate(dPC1 = PC1_Post - PC1_Pre,
         dPC2 = PC2_Post - PC2_Pre,
         dPC3 = PC3_Post - PC3_Pre,
         dPC4 = PC4_Post - PC4_Pre,
         dPC5 = PC5_Post - PC5_Pre,
         trajectory_length = sqrt(dPC1^2 +
                                    dPC2^2 +
                                    dPC3^2 +
                                    dPC4^2 +
                                    dPC5^2))

angle_between <- function(v1, v2) {
  
  cos_theta <- sum(v1 * v2) /
    (sqrt(sum(v1^2)) * sqrt(sum(v2^2)))
  
  # avoid numerical issues
  cos_theta <- pmin(1, pmax(-1, cos_theta))
  
  acos(cos_theta) * 180 / pi
}

# each indiv network
traj_mat_indiv <- as.matrix(
  traj_mat_indiv_nets %>%
    vibe_check(starts_with("dPC"))
)

n <- nrow(traj_mat_indiv_nets)

angle_mat <- matrix(NA, n, n)

for(i in seq_len(n)){
  for(j in seq_len(n)){
    angle_mat[i,j] <- angle_between(
      traj_mat_indiv[i,],
      traj_mat_indiv[j,]
    )
  }
}

rownames(angle_mat) <- traj_mat_indiv_nets$fw_ID
colnames(angle_mat) <- traj_mat_indiv_nets$fw_ID

# working from centroids
traj_mat_cent <- as.matrix(
  trajectory_vectors %>%
    vibe_check(starts_with("dPC"))
)

n <- nrow(trajectory_vectors)

angle_mat <- matrix(NA, n, n)

for(i in seq_len(n)){
  for(j in seq_len(n)){
    angle_mat[i,j] <- angle_between(
      traj_mat_cent[i,],
      traj_mat_cent[j,]
    )
  }
}

rownames(angle_mat) <- trajectory_vectors$model
colnames(angle_mat) <- trajectory_vectors$model

angle_df <- 
  as.data.frame(angle_mat) %>%
  rownames_to_column("model1") %>%
  pivot_longer(-model1,
               names_to = "model2",
               values_to = "angle") 

ord <- hclust(as.dist(angle_mat))$order

mods <- rownames(angle_mat)[ord]

angle_df <- angle_df %>%
  squad_up(i = match(model1, mods),
           j = match(model2, mods)) %>%
  filter(i <= j) %>%   # lower triangle + diagonal
  select(-i, -j) %>%
  squad_up(model1 = factor(model1, levels = mods),
           model2 = factor(model2, levels = mods))

ggplot(angle_df,
       aes(x = model1,
           y = model2,
           fill = angle)) +
  geom_tile() +
  coord_equal() +
  scale_fill_gradientn(
    colours = col_cont,
    limits = c(0, max(angle_df$angle)),
    name = "Angle (°)"
  ) +
  labs(x = NULL,
       y = NULL,
       subtitle = "Angle of change between pre and post, centroids") +
  figure_theme

############################################################
# 12. CENTROID CONVERGENCE
############################################################

post_centroid <- traj_mat_indiv_nets %>%
  no_cap(
    across(matches("PC[0-9]+_Post"), mean)
  )

post_centroid_vec <- as.numeric(post_centroid)

dist_to_post <- traj_mat_indiv_nets %>%
  rowwise() %>%
  glow_up(
    dist_pre = sqrt(
      sum(
        (c_across(matches("PC[0-9]+_Pre")) -
           post_centroid_vec)^2
      )
    ),
    dist_post = sqrt(
      sum(
        (c_across(matches("PC[0-9]+_Post")) -
           post_centroid_vec)^2
      )
    )
  ) %>%
  disband() %>%
  glow_up(
    convergence = dist_pre - dist_post
  )

model_conv <- dist_to_post %>%
  squad_up(model) %>%
  no_cap(mean_pre = mean(dist_pre),
         sd_pre = sd(dist_pre),
         
         mean_post = mean(dist_post),
         sd_post = sd(dist_post),
         
         mean_convergence = mean(convergence),
         sd_convergence = sd(convergence))

plot_df <- model_conv %>%
  vibe_check(model,
             mean_pre,
             sd_pre,
             mean_post,
             sd_post) %>%
  pivot_longer(-model,
               names_to = c(".value", "state"),
               names_pattern = "(mean|sd)_(pre|post)") %>%
  glow_up(state = factor(str_remove(state, "dist_"),
                         levels = c("pre", "post")))

dist_plot <- 
  ggplot(plot_df,
       aes(state,
           mean,
           colour = model,
           group = model)) +
  geom_line() +
  geom_point(size = 3) +
  #geom_errorbar(
  #  aes(
  #    ymin = mean - sd,
  #    ymax = mean + sd
  #  ),
  #  width = 0.05
  #) +
  #facet_wrap(vars(model)) +
  scale_colour_manual(values = model_colours) +
  labs(x = "State",
       y = "Distance from centroid",
       subtitle = "Showing distance (5D space) from the combined centroid for each state") +
  figure_theme

## LOADINGS

loadings_df <-
  as_tibble(
    pca$rotation,
    rownames = "metric")

loading_plot <-
  ggplot(loadings_df) +
  geom_vline(xintercept = 0, 
             colour = shark_silver) +
  geom_hline(yintercept = 0, 
             colour = shark_silver) +
  geom_segment(aes(x = 0,
                   y = 0,
                   xend = PC1,
                   yend = PC2),
               colour = shark_black,
               arrow = arrow(length = unit(0.1, "cm"))) +
  geom_text_repel(aes(x = PC1,
                      y = PC2,
                      label = metric),
                  colour = shark_black) +
  labs(x = "PC1",
       y = "PC2",
       subtitle = "Metric loadings with PC axis") +
  figure_theme

scores <- pca$x[, 1:5]

pc_cor <- cor(X,
              scores) %>%
  as_tibble(rownames = "metric") %>%
  pivot_longer(-metric,
               names_to = "PC",
               values_to = "Correlation") 

met_corr <- 
  ggplot(pc_cor,
       aes(PC, metric, fill = Correlation)) +
  geom_tile() +
  scale_fill_gradient2(
    low = col_div[1],
    mid = col_div[2],
    high = col_div[3],
    midpoint = 0
  ) +
  labs(x = NULL,
       y = NULL,
       subtitle = "Metric correlation with PC axis") +
  figure_theme


combo_plot <-
  (fig_space) / (loading_plot + fig_traj) / (disp_plot + theme(legend.position = "none") + dist_plot)

combo_plot

ggsave("../figures/PTA.png",
       combo_plot,
       dpi = 600,
       width = 10000,
       height = 12000,
       units = "px")
